apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo-project
  namespace: my-space
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2 
  selector:
    matchLabels:
      app: mo-project
  template:
    metadata:
      labels:
        app: mo-project
    spec:
      containers:
      - name: mo-project
        image: moritse/dockerhub:mydemo
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: mo-project
  namespace: my-space
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-balancing-enabled: 'true'
spec:
  type: LoadBalancer
  selector:
    app: mo-project
  ports:
  - port: 80
    targetPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: mo-project
  namespace: my-space
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-balancing-enabled: 'true'
spec:
  type: LoadBalancer
  selector:
    app: mo-project
  ports:
  - port: 80
    targetPort: 80


---
